### ISSUE TITLE
Error in Tuning Ensembles

### ISSUE THREAD

**Issue by bdav56** [business-science/modeltime.ensemble#31]
I am working on the ensembles portion of the Business Science Forecasting Course. Each time I attempt to tune parameters within the ensemble_model_spec(), I receive the error below. It works when I choose parameters like penalty and mixture manually, but not when I use tune(). I am using the development version of the model.ensemble package:

! `...` must be empty.
:heavy_multiplication_x: Problematic argument:
• ..1 = metric
:information_source: Did you forget to name an argument?

**Comment by trentonpulsipher** [comment]
I'm also seeing the same issue.
`Error in tune::show_best(., metric, n = 1) :
`...` must be empty.
✖ Problematic argument:
• ..1 = metric
ℹ Did you forget to name an argument?`

**Comment by mdancho84** [comment]
I'll do my best to fix this week

**Comment by trentonpulsipher** [comment]
What's the update or ETA on this issue (and the [related issue](https://github.com/business-science/modeltime.ensemble/issues/30))?

**Comment by mdancho84** [comment]
Should be fixed now.

**Comment by Arnold-Kakas** [comment]
Hi @mdancho84, I think this is still not working, I get the same error:
Error in `tune::show_best()`:
! `...` must be empty.
✖ Problematic argument:
• ..1 = metric
ℹ Did you forget to name an argument?

+ would it be possible to add metric as an argument?
